ocha_key_figures.settings:
  type: config_object
  label: 'OCHA Key Figures settings'
  mapping:
    ocha_api_url:
      type: string
      label: 'OCHA API Url'
    ocha_api_key:
      type: string
      label: 'OCHA API Key'
    enable_json_ld:
      type: boolean
      label: 'Enable JSON-LD'
    max_age:
      type: integer
      label: 'Max age for cache'
